// Estates.Core/Deck.cs — the DEALERLESS deck shuffle, used by GameReplay to recompute
// the jointly-generated deck order. Every random event (incl. the deck order) is
// generated by ALL seats' committed→revealed entropy, so no single machine — not
// even the host — chooses it. This must be byte-for-byte the TS reference (the
// canonical state hash includes deckOrder), so it is cross-validated by the
// conformance "deck" vector.
//
// Mirrors exactly:
//   commitEntropy   = hex(sha256(secret))
//   combineSeedBound= participant-bound fold (gameId ‖ per seat: seat‖pub‖commit‖reveal)
//   permutation     = Fisher–Yates with rejection sampling over a sha256 counter PRNG
//   dealerlessDeckOrder = per-deck domain-separated permutation from that one seed
using System.Security.Cryptography;
using System.Text;

namespace Estates.Core;

/// <summary>A signed-shuffle participant: a seat, its key, its prior entropy
/// commitment, and the revealed secret that must open that commitment.</summary>
public readonly record struct SeedParty(int Seat, string Pub, string Commitment, byte[] Reveal);

public static class Deck
{
    public const int MAX_DECK_SIZE = 1 << 16; // 65536 — far above any real ESTATES set

    /// <summary>commitEntropy(secret) = hex(sha256(secret)).</summary>
    public static string CommitEntropy(byte[] secret) => Tx.ToHex(SHA256.HashData(secret));

    private static bool IsTableIdHex(string? x)
        => x is { Length: 64 } && x.All(c => (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'));

    private static bool IsLowerHexEven(string? x)
        => x is not null && x.Length % 2 == 0 && x.Length > 0 && x.All(c => (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'));

    private static byte[] U32be(int n) => new[] { (byte)((n >> 24) & 0xff), (byte)((n >> 16) & 0xff), (byte)((n >> 8) & 0xff), (byte)(n & 0xff) };

    /// <summary>Participant-bound seed combination. Verifies every reveal opens its
    /// commitment, rejects duplicate seats/keys, folds (gameId ‖ for each party in
    /// seat order: seat‖pub‖commitment‖reveal) into the seed. Null on any
    /// inconsistency (total) — exactly like the TS combineSeedBound.</summary>
    public static byte[]? CombineSeedBound(IReadOnlyList<SeedParty> parties, string gameId)
    {
        if (!IsTableIdHex(gameId) || parties.Count == 0 || parties.Count > 64) return null;
        var seats = new HashSet<int>();
        var pubs = new HashSet<string>();
        var sorted = parties.OrderBy(p => p.Seat).ToList();
        using var ms = new MemoryStream();
        ms.Write(Encoding.ASCII.GetBytes("ESTATES_SHUFFLE_SEED_V1|"));
        ms.Write(Tx.FromHex(gameId));
        foreach (var p in sorted)
        {
            if (p.Seat < 0 || p.Seat > 63) return null;
            if (!IsLowerHexEven(p.Pub)) return null;
            if (p.Reveal is null) return null;
            if (p.Commitment is null || CommitEntropy(p.Reveal) != p.Commitment) return null; // reveal must open its commitment
            if (!seats.Add(p.Seat) || !pubs.Add(p.Pub)) return null;                          // no duplicate party
            ms.Write(U32be(p.Seat));
            ms.Write(Tx.FromHex(p.Pub));
            ms.Write(Tx.FromHex(p.Commitment));
            ms.Write(p.Reveal);
        }
        return SHA256.HashData(ms.ToArray());
    }

    /// <summary>Deterministic Fisher–Yates permutation of [0,n) from a seed (sha256
    /// counter PRNG), with rejection sampling so the modulo is exact/unbiased for any
    /// size — byte-for-byte the TS permutation.</summary>
    public static int[] Permutation(byte[] seed, int n)
    {
        if (n < 0 || n > MAX_DECK_SIZE) throw new ArgumentOutOfRangeException(nameof(n), $"permutation: n out of range (0..{MAX_DECK_SIZE})");
        var idx = new int[n];
        for (int i = 0; i < n; i++) idx[i] = i;
        byte[] pool = SHA256.HashData(seed);
        int p = 0;
        uint Next()
        {
            if (p + 4 > pool.Length) { pool = SHA256.HashData(pool); p = 0; }
            uint v = ((uint)pool[p] << 24) | ((uint)pool[p + 1] << 16) | ((uint)pool[p + 2] << 8) | pool[p + 3];
            p += 4;
            return v;
        }
        int DrawBelow(int bound)
        {
            long limit = (0x1_0000_0000L / bound) * bound;
            while (true) { uint r = Next(); if (r < limit) return (int)(r % (uint)bound); }
        }
        for (int i = n - 1; i > 0; i--)
        {
            int j = DrawBelow(i + 1);
            (idx[i], idx[j]) = (idx[j], idx[i]);
        }
        return idx;
    }

    /// <summary>The jointly-generated deck order for a live game: one participant-
    /// bound seed → an exact permutation per named deck (domain-separated so the
    /// decks are independent). Null on any inconsistent party set. Mirrors the TS
    /// dealerlessDeckOrder exactly.</summary>
    public static Dictionary<string, List<int>>? DealerlessDeckOrder(IReadOnlyList<SeedParty> parties, string gameId, IReadOnlyDictionary<string, int> deckSizes)
    {
        var baseSeed = CombineSeedBound(parties, gameId);
        if (baseSeed is null) return null;
        var order = new Dictionary<string, List<int>>();
        foreach (var name in deckSizes.Keys.OrderBy(k => k, StringComparer.Ordinal))
        {
            int nn = deckSizes[name];
            if (nn < 0 || nn > MAX_DECK_SIZE) return null;
            using var ms = new MemoryStream();
            ms.Write(baseSeed);
            ms.Write(Encoding.ASCII.GetBytes("ESTATES_DECK_ORDER_V1|deck:" + name));
            byte[] seed = SHA256.HashData(ms.ToArray());
            order[name] = Permutation(seed, nn).ToList();
        }
        return order;
    }
}
