// A live game's DECK ORDER is jointly generated by ALL seats (commit→reveal),
// recomputed identically by every peer — no single machine (incl. the host)
// chooses it. Backward compatible: without the entropy round, the declared order
// is used (the existing 40 table tests are unaffected).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { InMemoryRelay } from '@estates/chat';
import { gameIdentityFrom } from '@estates/channel';
import { NetTable, type NetworkMode } from '../src/index.ts';

const GID = 'a1'.repeat(32);

function lobby(masters: Uint8Array[]): { relay: InMemoryRelay; peers: NetTable[] } {
  const relay = new InMemoryRelay();
  const peers = masters.map((m, i) => new NetTable(relay, `p${i}`, () => {}, { identity: gameIdentityFrom(m, GID), gameId: GID }));
  for (const p of peers) p.connect();
  peers[0]!.createTable(masters.length, 'regtest' as NetworkMode);
  for (const p of peers) p.joinSeat();
  return { relay, peers };
}

test('every seat commits→reveals deck entropy; the live game deals from the JOINTLY-generated order', () => {
  const { peers } = lobby([new Uint8Array(32).fill(1), new Uint8Array(32).fill(2)]);
  for (const p of peers) p.commitDeckEntropy();   // commit phase
  for (const p of peers) p.revealDeckEntropy();    // reveal phase
  peers[0]!.start();                                // host starts

  const order = peers[0]!.state?.deckOrder;
  assert.ok(order, 'the game has a deck order');
  for (const name of ['Fate', 'Treasury']) {
    const a: readonly number[] = order![name]!;
    assert.deepEqual([...a].sort((x, y) => x - y), Array.from({ length: a.length }, (_, i) => i), `${name} is an exact permutation`);
  }
  // EVERY peer recomputed the SAME order (no divergence; deterministic from entropy)
  assert.deepEqual(peers[1]!.state?.deckOrder, order, 'both peers agree on the jointly-generated order');
  // it is not the trivial identity order (the entropy actually shuffled)
  assert.notDeepEqual(order!.Fate, Array.from({ length: order!.Fate!.length }, (_, i) => i));
});

test('different entropy → a different deck order (no single party fixes it)', () => {
  const run = (m0: number) => {
    const { peers } = lobby([new Uint8Array(32).fill(m0), new Uint8Array(32).fill(2)]);
    for (const p of peers) p.commitDeckEntropy();
    for (const p of peers) p.revealDeckEntropy();
    peers[0]!.start();
    return peers[0]!.state?.deckOrder?.Fate;
  };
  assert.notDeepEqual(run(1), run(5), 'changing a participant changes the order');
});

test('a reveal published BEFORE every seat has committed is REJECTED (commit-before-reveal soundness)', () => {
  const { peers } = lobby([new Uint8Array(32).fill(1), new Uint8Array(32).fill(2)]);
  peers[0]!.commitDeckEntropy();   // seat 0 commits
  peers[0]!.revealDeckEntropy();   // seat 0 reveals PREMATURELY — seat 1 has NOT committed yet → dropped by the gate
  peers[1]!.commitDeckEntropy();   // seat 1 commits (all committed now, but seat 0 already leaked early)
  peers[1]!.revealDeckEntropy();   // seat 1 reveals (valid)
  peers[0]!.start();
  // seat 0's early reveal was dropped and never re-sent, so the joint shuffle is
  // incomplete — the game must NOT seed a partial/biasable order. No single seat could
  // have chosen its entropy after seeing another's reveal.
  assert.equal(peers[0]!.state?.deckOrder, undefined, 'a premature reveal cannot seed the shuffle');
  assert.deepEqual(peers[1]!.state?.deckOrder, peers[0]!.state?.deckOrder, 'both peers agree (no order)');
});

test('backward compatible: without the entropy round, the game starts with the declared order', () => {
  const { peers } = lobby([new Uint8Array(32).fill(3), new Uint8Array(32).fill(4)]);
  peers[0]!.start(); // no deck entropy committed
  assert.ok(peers[0]!.state, 'game started (state exists)');     // (beacon may auto-roll past AWAIT_ROLL)
  assert.notEqual(peers[0]!.view().phase, 'lobby');
  assert.equal(peers[0]!.state?.deckOrder, undefined, 'no injected deck order (declared order)');
});
