import { HttpRelay } from './src/relay.ts';
const got = [];
const r = new HttpRelay('http://127.0.0.1:8788', 'probe-ch');
r.subscribe((p) => got.push(new TextDecoder().decode(p)));
await new Promise((x) => setTimeout(x, 600));
const w = new HttpRelay('http://127.0.0.1:8788', 'probe-ch');
w.publish(new TextEncoder().encode('hello-sse'));
await new Promise((x) => setTimeout(x, 1800));
console.log('received:', JSON.stringify(got));
process.exit(got.some((x) => x.includes('hello-sse')) ? 0 : 1);
